import type { Metadata } from 'next';
import { Anton } from 'next/font/google';
import './globals.css';
import Header from './components/layout/Header';
import Footer from './components/layout/Footer';

const anton = Anton({
	subsets: ['latin'],
	weight: '400',
	style: 'normal',
});

export const metadata: Metadata = {
	title: "Keshopan's Portfolio",
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={anton.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
